Repository smdogroup/funtofem, pull requests merged in 2023-08, with the labels that each got.

#205 Fully coupled FUN3D+TACS discipline derivative tests
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/meshes/laminar/Adjoint/.DS_Store
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/meshes/laminar/Flow/fun3d.nml
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/meshes/laminar/Flow/miniMesh.b8.ugrid
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/meshes/laminar/Flow/miniMesh.mapbc
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/meshes/laminar/Flow/moving_body.input
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/meshes/laminar/Flow/perturb.input
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/meshes/nastran_CAPS.bdf
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/meshes/nastran_CAPS.dat
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/results/fun3d-tacs-driver.txt
  tests/fun3d_tests/fully_coupled_disc_deriv/laminar/test_fun3d_tacs.py
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/meshes/nastran_CAPS.bdf
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/meshes/nastran_CAPS.dat
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/meshes/turbulent/Adjoint/.DS_Store
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/meshes/turbulent/Flow/fun3d.nml
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/meshes/turbulent/Flow/miniMesh.b8.ugrid
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/meshes/turbulent/Flow/miniMesh.mapbc
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/meshes/turbulent/Flow/moving_body.input
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/meshes/turbulent/Flow/perturb.input
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/results/fun3d-tacs-driver.txt
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AE/test_fun3d_tacs.py
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/meshes/nastran_CAPS.bdf
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/meshes/nastran_CAPS.dat
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/meshes/turbulent/Adjoint/.DS_Store
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/meshes/turbulent/Flow/fun3d.nml
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/meshes/turbulent/Flow/miniMesh.b8.ugrid
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/meshes/turbulent/Flow/miniMesh.mapbc
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/meshes/turbulent/Flow/moving_body.input
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/meshes/turbulent/Flow/perturb.input
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/results/fun3d-tacs-driver.txt
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_AT/test_fun3d_tacs.py
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/meshes/nastran_CAPS.bdf
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/meshes/nastran_CAPS.dat
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/meshes/turbulent/Adjoint/.DS_Store
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/meshes/turbulent/Flow/fun3d.nml
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/meshes/turbulent/Flow/miniMesh.b8.ugrid
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/meshes/turbulent/Flow/miniMesh.mapbc
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/meshes/turbulent/Flow/moving_body.input
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/meshes/turbulent/Flow/perturb.input
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/results/fun3d-tacs-driver.txt
  tests/fun3d_tests/fully_coupled_disc_deriv/turb_ATE/test_fun3d_tacs.py
Labels: documentation, enhancement, testing

#212 Fully Coupled FUN3D-TACS Coordinate Derivative Tests
  funtofem/interface/fun3d_interface.py
  funtofem/interface/test_solver.py
  funtofem/model/body.py
  tests/fun3d_tests/README.md
  tests/fun3d_tests/meshes/turbulent_miniMesh/Adjoint/.gitignore
  tests/fun3d_tests/meshes/turbulent_miniMesh/Flow/fun3d.nml
  tests/fun3d_tests/meshes/turbulent_miniMesh/Flow/miniMesh.mapbc
  tests/fun3d_tests/meshes/turbulent_miniMesh/Flow/moving_body.input
  tests/fun3d_tests/meshes/turbulent_miniMesh/Flow/perturb.input
  tests/fun3d_tests/meshes/turbulent_miniMesh/nastran_CAPS.bdf
  tests/fun3d_tests/meshes/turbulent_miniMesh/nastran_CAPS.dat
  tests/fun3d_tests/test_fun3d_coordinate_derivatives.py
  tests/fun3d_tests/test_funtofem_aero_coord.py
  tests/fun3d_tests/test_funtofem_aero_struct_morph.py
  tests/fun3d_tests/test_funtofem_struct_coord.py
Labels: enhancement, testing

#218 Tacs Unsteady Adjoint Fixes
  funtofem/driver/funtofem_nlbgs_driver.py
  funtofem/interface/tacs_interface_unsteady.py
  funtofem/interface/test_solver.py
  tests/unit_tests/framework_unsteady/README.md
  tests/unit_tests/framework_unsteady/images/unsteady_tacs_discipline_tests.drawio.png
  tests/unit_tests/framework_unsteady/input_files/stiffened_plate.csm
  tests/unit_tests/framework_unsteady/mesh_plate.py
  tests/unit_tests/framework_unsteady/test_framework_adjoint_eqns.py
  tests/unit_tests/framework_unsteady/test_framework_unsteady.py
  tests/unit_tests/framework_unsteady/test_funtofem_unsteady_aero_coord.py
  tests/unit_tests/framework_unsteady/test_funtofem_unsteady_struct_coord.py
  tests/unit_tests/framework_unsteady/test_tacs_adjoint_eqns.py
  tests/unit_tests/framework_unsteady/test_tacs_driver_unsteady_coordinate.py
  tests/unit_tests/framework_unsteady/test_tacs_interface_unsteady.py
  tests/unit_tests/framework_unsteady/test_unsteady_solvers.py
Labels: bug, testing
